export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const DOCTORS_SUCCESS = 'DOCTORS_SUCCESS';
export const DOCTORS_FAIL = 'DOCTORS_FAIL';
export const HOSPITALS_SUCCESS = 'HOSPITALS_SUCCESS';
export const HOSPITALS_FAIL = 'HOSPITALS_FAIL';
export const SUPPLIERS_SUCCESS = 'SUPPLIERS_SUCCESS';
export const SUPPLIERS_FAIL = 'SUPPLIERS_FAIL';
export const VOLUNTEERS_SUCCESS = 'VOLUNTEERS_SUCCESS';
export const VOLUNTEERS_FAIL = 'VOLUNTEERS_FAIL';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
